FROM node:18.14.0-alpine3.17

WORKDIR /usr/src/app

COPY --chown=node:node package.json package-lock.json ./

RUN npm ci

COPY --chown=node:node . .

RUN rm -rf .git/ && rm -rf .github/ && rm -rf .env* && rm -rf .vscode

RUN npm run prisma:generate

RUN npm run build

RUN npm prune --production

USER node

ENV NODE_ENV production

EXPOSE 3000

#CMD ["npm", "run", "start"]
#CMD ["npm", "run", "start:migrate:prod"]
