import { Login } from '@/components/auth/Login'
import { H1 } from '@/components/core/Typography'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>POAP Aragon Claim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <H1>Welcome to POAP Aragon Claim</H1>
        <Login />
      </main>
    </>
  )
}
