---
name: app-build-dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
      - 'Dockerfile*'
      - '.env*'
      - '.vscode'
      - '.dockerignore'
      - 'docker.env'
      # - '.github/**'

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        if: github.ref == 'refs/heads/test'
        run: npm run test:e2e

  docker-release:
    runs-on: ubuntu-latest
    needs: setup-and-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Git hash and Timestamp in seconds
        id: vars
        run: |
          echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE_IN_SECS=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
          tags: |
            type=ref,event=branch
            type=sha,event=branch,prefix=commit-hash-,format=short,enable=${{ github.ref_type != 'tag' }}
            #type=raw,value=commit1-{{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Show Docker Tags and Labels
        run: |
          echo "TAGS: ${{ steps.meta.outputs.tags }}"
          echo "LABELS: ${{ steps.meta.outputs.labels }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}               ## i.e. ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prod
          build-args: |
             COMMIT_SHA=${{ steps.vars.outputs.GIT_HASH_SHORT }}
             ENVIRONMENT=development
          push: false         ## set false temp : ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository }}:develop-${{ steps.vars.outputs.DATE_IN_SECS }}
          labels: ${{ steps.meta.outputs.labels }}
