---
name: client-build

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'DOPS-449*' ## temporal branch for testing only
    paths-ignore:
      # - 'README.md'
      - 'Dockerfile*'
      - '.env.local'
      - '.env'
      - '.vscode'
      - '.dockerignore'
      - 'docker.env'
      - '.github/**'

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        if: github.ref == 'refs/heads/test'
        run: npm run test:e2e

  set-myvars:
    runs-on: ubuntu-latest
    needs: [setup-and-build]
    outputs:
      BRANCH_NAME: ${{ steps.myvars.outputs.BRANCH_NAME }}
      GIT_HASH_SHORT: ${{ steps.myvars.outputs.GIT_HASH_SHORT }}
      DATE_IN_SECS: ${{ steps.myvars.outputs.DATE_IN_SECS }}
      CURRENT_ENVIRONMENT: ${{ steps.myvars.outputs.CURRENT_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get branch name, git commit hash and current time in secs
        id: myvars
        run: |
          branchname=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )
          echo "BRANCH_NAME=$branchname" >> $GITHUB_OUTPUT
          echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE_IN_SECS=$(date +%s)" >> $GITHUB_OUTPUT
          if [ "$branchname" = "develop" ]; then
            echo "CURRENT_ENVIRONMENT=development" >> $GITHUB_OUTPUT
          elif [ "$branchname" = "main" ]; then
            echo "CURRENT_ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "BRANCH_NAME=test" >> $GITHUB_OUTPUT
            echo "CURRENT_ENVIRONMENT=testing" >> $GITHUB_OUTPUT
          fi

  docker-release:
    runs-on: ubuntu-latest
    needs: [set-myvars]
    if: needs.set-myvars.outputs.CURRENT_ENVIRONMENT != ''
    environment: ${{ needs.set-myvars.outputs.CURRENT_ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
          tags: |
            type=sha,event=branch,prefix=commit-,format=short,enable=${{ github.ref_type != 'tag' }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prod
          build-args: |
            COMMIT_SHA=${{ needs.set-myvars.outputs.GIT_HASH_SHORT }}
            ENVIRONMENT=${{ needs.set-myvars.outputs.CURRENT_ENVIRONMENT }}
            NEXT_PUBLIC_ALCHEMY_ID=${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
            NEXT_PUBLIC_LOGIN_KEY=${{ secrets.NEXT_PUBLIC_LOGIN_KEY }}
            NEXT_PUBLIC_GRAPHQL_BASE_URL=${{ vars.NEXT_PUBLIC_GRAPHQL_BASE_URL }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository }}:${{ needs.set-myvars.outputs.BRANCH_NAME }}
            ghcr.io/${{ github.repository }}:${{ needs.set-myvars.outputs.BRANCH_NAME }}-${{ needs.set-myvars.outputs.DATE_IN_SECS }}
          labels: ${{ steps.meta.outputs.labels }}
